
executables:
  avl-example:
    main: Example.hs

    dependencies:
    - AVL
    - aeson
    - base
    - bytestring
    - cborg
    - containers
    - data-default
    - directory
    - exceptions
    - hashable
    - hedis
    - lens
    - mtl
    - serialise
    - text

    default-extensions:
    - DataKinds
    - DeriveGeneric
    - DeriveAnyClass
    - DerivingStrategies
    - FlexibleInstances
    - GeneralizedNewtypeDeriving
    - MultiParamTypeClasses
    - ViewPatterns
    - FlexibleContexts
    - TypeApplications
    - ConstraintKinds
    - MonoLocalBinds
    - TemplateHaskell
    - BlockArguments
